### ISSUE TITLE
Prepare script to run detections on the downloaded sample of images

### ISSUE THREAD

**Issue by valentinitnelav** [stark-t/PAI_diptera#5]
The goal is to try to speed up the manual annotation process, by putting automatically bounding boxes using the weights from paper 1. Then we will manually check and adjust the bounding boxes. then we will crop the insects based on the coordinates of the bounding boxes and use them for scene/image classification.

Use the weights from paper 1 with the optimal conf and IOI threshold.

The input should be a folder of images that corresponds to a family. I'll run this family by family as it is easier to manage internally. Also when we will use the GVV-VIA image annotator for checking and manually adjusting the boxes, it has a problem when we start loading more than 3000-5000 images per folder (the web browser will crash).

**Comment by valentinitnelav** [comment]
Test if I can send images to the EVE cluster from the RStudio server (it has a Linux terminal that i could use).

- doesn't seem to work. I do not get access to EVE from the terminal of RStudio server.

**Comment by valentinitnelav** [comment]
On EVE I set the yolov5 repository in the `./architectures/` directory, then I set a virtual environment for yolov5 at `./env/yolov5/`.

This is needed so that I can run detections on the raw images indexed by GBIF.

```sh
cd /data/idiv_knight/Valentin/ 
git clone https://github.com/stark-t/PAI_diptera.git
cd PAI_diptera/


cd architectures/
git clone https://github.com/ultralytics/yolov5


# Create an environment with the needed dependencies/requirements
cd ..
mkdir env
module purge 
# Load these modules at Christian Krause’s recommendation:
module load fosscuda/2020b TensorFlow/2.5.0
# Create a virtual environment named yolov5
python -m venv env/yolov5
# Activate virtual environment
source env/yolov5/bin/activate
# Install the requirements
pip install --upgrade pip
pip install -r architectures/yolov5/requirements.txt
deactivate
``` 

The `pip install -r architectures/yolov5/requirements.txt` gave this error
```
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.19.4
    Not uninstalling numpy at /gpfs0/global/software/easybuild-broadwell/software/SciPy-bundle/2020.11-fosscuda-2020b/lib/python3.8/site-packages, outside environment /gpfs1/data/idiv_knight/Valentin/PAI_diptera/env/yolov5
    Can't uninstall 'numpy'. No files were found to uninstall.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.5.0 requires numpy~=1.19.2, but you have numpy 1.24.2 which is incompatible.
tensorflow 2.5.0 requires six~=1.15.0, but you have six 1.16.0 which is incompatible.
Successfully installed numpy-1.24.2
```
I manually installed numpy=1.19.2 & six=1.15.0:
```sh
pip install six==1.15.0 # all good
```

```sh
pip install numpy=1.19.2 # gives this other error
```

```
Collecting numpy==1.19.2
  Using cached numpy-1.19.2-cp38-cp38-manylinux2010_x86_64.whl (14.5 MB)
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.19.4
    Not uninstalling numpy at /gpfs0/global/software/easybuild-broadwell/software/SciPy-bundle/2020.11-fosscuda-2020b/lib/python3.8/site-packages, outside environment /gpfs1/data/idiv_knight/Valentin/PAI_diptera/env/yolov5
    Can't uninstall 'numpy'. No files were found to uninstall.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
matplotlib 3.7.0 requires numpy>=1.20, but you have numpy 1.19.2 which is incompatible.
Successfully installed numpy-1.24.2
```

Not sure how to solve this at the moment and if it will create problems. Proceed further and I'll need to come back to this after I double check with the IT admin of EVE.

**Comment by valentinitnelav** [comment]
The environment settings from above lead to such errors when running https://github.com/stark-t/PAI_diptera/blob/main/data/gbif_occurences/detect_insects_yolov5.sh

```
Traceback (most recent call last):
  File "/gpfs1/data/idiv_knight/Valentin/PAI_diptera/env/yolov5/lib/python3.8/site-packages/torch/__init__.py", line 172, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/software/easybuild-broadwell/software/Python/3.8.6-GCCcore-10.2.0/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /gpfs1/data/idiv_knight/Valentin/PAI_diptera/env/yolov5/lib/python3.8/site-packages/torch/lib/../../nvidia/cublas/lib/libcublas.so.11: symbol cublasLtHSHMatmulAlgoInit, version libcublasLt.so.11 not defined in file libcublasLt.so.11 with link time reference

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "detect.py", line 37, in <module>
    import torch
  File "/gpfs1/data/idiv_knight/Valentin/PAI_diptera/env/yolov5/lib/python3.8/site-packages/torch/__init__.py", line 217, in <module>
    _load_global_deps()
  File "/gpfs1/data/idiv_knight/Valentin/PAI_diptera/env/yolov5/lib/python3.8/site-packages/torch/__init__.py", line 178, in _load_global_deps
    _preload_cuda_deps()
  File "/gpfs1/data/idiv_knight/Valentin/PAI_diptera/env/yolov5/lib/python3.8/site-packages/torch/__init__.py", line 158, in _preload_cuda_deps
    ctypes.CDLL(cublas_path)
  File "/software/easybuild-broadwell/software/Python/3.8.6-GCCcore-10.2.0/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /gpfs1/data/idiv_knight/Valentin/PAI_diptera/env/yolov5/lib/python3.8/site-packages/nvidia/cublas/lib/libcublas.so.11: symbol cublasLtHSHMatmulAlgoInit, version libcublasLt.so.11 not defined in file libcublasLt.so.11 with link time reference
```

I set then 2 environments: 

- yolov5_2020b_tf25 (the one from above)
```sh
module load fosscuda/2020b TensorFlow/2.5.0
python -m venv env/yolov5_2020b_tf25
```
- yolov5_2019b_tf21
```sh
module load fosscuda/2019b TensorFlow/2.1.0-Python-3.7.4
python -m venv env/yolov5_2019b_tf21
```

But the second one gives this error:
```
Traceback (most recent call last):
  File "detect.py", line 261, in <module>
    main(opt)
  File "detect.py", line 256, in main
    run(**vars(opt))
  File "/gpfs1/data/idiv_knight/Valentin/PAI_diptera/env/yolov5_2019b_tf21/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "detect.py", line 98, in run
    model = DetectMultiBackend(weights, device=device, dnn=dnn, data=data, fp16=half)
  File "/gpfs1/data/idiv_knight/Valentin/PAI_diptera/architectures/yolov5/models/common.py", line 345, in __init__
    model = attempt_load(weights if isinstance(weights, list) else w, device=device, inplace=True, fuse=fuse)
  File "/gpfs1/data/idiv_knight/Valentin/PAI_diptera/architectures/yolov5/models/experimental.py", line 88, in attempt_load
    model.append(ckpt.fuse().eval() if fuse and hasattr(ckpt, 'fuse') else ckpt.eval())  # model in eval mode
  File "/gpfs1/data/idiv_knight/Valentin/PAI_diptera/architectures/yolov5/models/yolo.py", line 144, in fuse
    m.conv = fuse_conv_and_bn(m.conv, m.bn)  # update conv
  File "/gpfs1/data/idiv_knight/Valentin/PAI_diptera/architectures/yolov5/utils/torch_utils.py", line 262, in fuse_conv_and_bn
    fusedconv.weight.copy_(torch.mm(w_bn, w_conv).view(fusedconv.weight.shape))
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`
```

I'll have to contact the cluster admin team.

Meanwhile, I can try to test things on the Clara cluster.

**Comment by valentinitnelav** [comment]
Could these be problems related to the fact that I use older yolov5 weights (from paper 1)? The training environment was different as it was conducted on the Clara cluster and now I use them on the EVE cluster. But if this is the case, then this is a huge issue of reproducibility in general.

Edit / Note to self: 
I just talked with Christian from IT and he looked into the weights file and he thinks this is not an issue generated by the weights themselves, but it has to be from some conflicting CUDA dependencies in the local environment vs the global one of the cluster. One fast solution is to move things to the Clara cluster or check for the dependency conflicts by looking on what `pip list` gives with and without doing the part `module load ...`

**Comment by valentinitnelav** [comment]
Ok, the environment problem seems to be solved.

I do not need so many things from the tool chain as per first advise from IT. 
This works perfectly without dependencies conflicts:
```sh
cd /data/idiv_knight/Valentin/PAI_diptera/
module purge 
module spider Python
#     Versions:
#        Python/2.7.14-bare
#        Python/2.7.14
#        Python/2.7.15-bare
#        Python/2.7.15
#        Python/2.7.16
#        Python/2.7.18
#        Python/3.6.4
#        Python/3.6.6
#        Python/3.7.4
#        Python/3.8.6

module spider Python/3.8.6

# You will need to load all module(s) on any one of the lines below before the "Python/3.8.6" module is available to load.
#      GCCcore/10.2.0

module load GCCcore/10.2.0
module load Python/3.8.6
python -m venv env/yolov5_simplified
source env/yolov5_simplified/bin/activate
pip install --upgrade pip
pip install -r architectures/yolov5/requirements.txt
deactivate
```


These were the modules that were available for my environment. It seems that the rest is overkill for my needs and creates issues.

```sh
module --terse list | sort
# GCCcore/10.2.0
# zlib/1.2.11
# binutils/2.35
# bzip2/1.0.8
# ncurses/6.2
# libreadline/8.0
# Tcl/8.6.10
# SQLite/3.33.0
# XZ/5.2.5
# GMP/6.2.0
# libffi/3.3
# Python/3.8.6
```

**Comment by valentinitnelav** [comment]
Ok, so I run again into the `RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling cublasCreate(handle)` but this seems actually to be a GPU RAM issue - see https://discuss.pytorch.org/t/cuda-error-cublas-status-not-initialized-when-calling-cublascreate-handle/125450/2

For our case, this particularly happens when I use the option `sbatch --constraint='a100-vram-40G'`. I think then it is trying to make use of a gpu:nvidia-a100 with 80 GB of memory and at the time of the execution it happens that it has 40GB available, but then it immediately runs out of RAM. This might explain why I also saw `39401MiB / 40960MiB` in the `nvidia-smi` output in the log file:

```
========================================================================
Output of: nvidia-smi
========================================================================
Wed Feb 22 19:31:25 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.48.07    Driver Version: 515.48.07    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100-PCI...  On   | 00000000:CA:00.0 Off |                    0 |
| N/A   69C    P0   246W / 250W |  39401MiB / 40960MiB |     96%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
```

However, not sure if this is the explanation.
But for detection purposes, when I do not care that much about the GPU RAM, then better just ask for an entire GPU like `-G tesla-v100:1` or `--gpus tesla-v100:1` or whatever available GPU, like `-G 1` or `--gpus 1`. See https://wiki.ufz.de/eve/index.php/Submitting_Jobs_SLURM#GPUs

**Comment by valentinitnelav** [comment]
I managed to run a detect.py script on the GBIF images using the weights from paper 1 (yolov5-s) like this:

Set the environment - see https://github.com/stark-t/PAI_diptera/issues/5#issuecomment-1440455055

I transferred data to the cluster:
```sh
rsync -avhP \
/home/vs66tavy/idiv-mount/groups/Artificial-Intelligence/pai_p3_diptera_families/data/gbif_occurences/sampled/images \
stefanv@frontend1.eve.ufz.de:/data/idiv_knight/Valentin/PAI_diptera/data/gbif_occurences/sampled
```
Transfer the YOLOv5 trained weights from paper 1 (order detector). See the weights used with https://github.com/stark-t/PAI/blob/main/scripts/cluster/yolov5_detect_s_640_rtx.sh

```sh
# On EVE’s terminal:
cd architectures/yolov5
mkdir weights_paip1

# On local PC terminal:
rsync -avhP ~/Nextcloud/yolo-runs-clara/PAI/3219884_yolov5_s_img640_b8_e300_hyp_custom/weights/best.pt stefanv@frontend1.eve.ufz.de:/data/idiv_knight/Valentin/PAI_diptera/architectures/yolov5/weights_paip1

# Rename them for clarity
cd weights_paip1
mv best.pt s_best.pt

# This was needed because there were no logs_detect_jobs directory yet created
cd ../..
mkdir logs_detect_jobs
```

Prepare the txt file with the path to each image
```sh
# On EVE
cd /data/idiv_knight/Valentin/PAI_diptera/data/gbif_occurences/

python get_img_paths.py \
--img_dir /data/idiv_knight/Valentin/PAI_diptera/data/gbif_occurences/sampled/images/ \
--output /data/idiv_knight/Valentin/PAI_diptera/data/gbif_occurences/sampled/images.txt
# 41309 lines written to /data/idiv_knight/Valentin/PAI_diptera/data/gbif_occurences/sampled/images.txt
```

Run the detection job like this, using `detect_insects_yolov5.sh`
```sh
sbatch --constraint='a100-vram-40G' --time='0-10:00:00' \
/data/idiv_knight/Valentin/PAI_diptera/data/gbif_occurences/detect_insects_yolov5.sh \
/data/idiv_knight/Valentin/PAI_diptera \
architectures/yolov5/weights_paip1/s_best.pt \
data/gbif_occurences/sampled/images.txt \
640 \
0.3 \
0.6 \
1000

# Submitted batch job 31298485
# Slurm Job_id=31298485 Name=detect_y5 Ended, Run time 00:56:00, COMPLETED, ExitCode 0
```

Count the number of txt files with predictions:
```sh
cd /data/idiv_knight/Valentin/PAI_diptera/architectures/yolov5/runs/detect/job_31298485/predlbl_imgsize_640_maxdet_1000_conf_0.3_iou_0.6/labels
ls -1 *.txt | wc -l
# 37576
```
